version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./creds:/app/creds
      - ./src:/app/src
    environment:
      - HOST=0.0.0.0
    command: python -m src.api.run
    restart: unless-stopped 