services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /Users/nullelement/OneDrive - Office 365 Fontys/synthpub-db:/app/db
    environment:
      - SYNTHPUB_HOST=0.0.0.0
    command: python -m api.run
    restart: unless-stopped 